name: Build on push

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3

      - name: "Use Node.js 19.x"
        uses: actions/setup-node@master
        with:
          node-version: 19.x

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build-prod

      - name: Release kittens manager
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          name: "latest"
          prerelease: true
          files: |
            dist/*
